baseurl = "https://snakemittens.com/"
languageCode = "en-us"
title = "snakemittens"
theme = "infact"
Paginate = 10

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
  twitterName = "thesnakemittens"
  githubName = "thesnakemittens"
  description = "...as useless as mittens for snakes"
  google_analytics = "UA-xxxxxx-xx"
  hideShareOptions = true